<a href="https://colab.research.google.com/github/mouni001/AI/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
#intro to tensors
#A way to represent data


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()


7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector.ndim #number dimention of of the vector
#only look at the pair of squaer brackts

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
 TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png

SyntaxError: invalid syntax (<ipython-input-24-4a8d36e4d0ee>, line 1)

### Random Tensors


In [1]:
#Random tensors
why random tensors?

random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those random numbers
to better represent the data

'start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers'

torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [4]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.8584, 0.1119, 0.2560, 0.6149],
        [0.2110, 0.2176, 0.3771, 0.0281],
        [0.5777, 0.9467, 0.5672, 0.4039]])

In [5]:
random_tensor.ndim

2

In [6]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones




In [7]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
 zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
ones = torch.ones(size=(3,4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
# use torch.range() but deprecating use aragange instead
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
one_to_ten = torch.arange(start =0, end=1000, step =77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [19]:
# creating tensors like
tens_zeros = torch.zeros_like(one_to_ten)
tens_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatype

**Notes:** Tensor datatype is one of the 3 big errors you'll run into Pytorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the irght device

In [4]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None, #what data type is the tensor (e.g.: float32 or float16)
                               device= None, #what device is your tensor on
                               requires_grad=False)#wether or not to track gradient tensors with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [6]:
float_32_tensor.dtype

torch.float32

In [7]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [8]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [9]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### getting information from tensors (tensors attributes)

1. Tensors not right datatype-to do get datatype from tensor, can use 'tensor.dtype'
2. Tensors not right shape-to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the irght device-to get device from a tensor, can use 'tensor.device'

In [11]:
# create a tensor
some_tensor =torch.rand(3,4)
some_tensor

tensor([[0.9419, 0.3062, 0.9409, 0.7417],
        [0.2304, 0.7320, 0.5334, 0.1238],
        [0.8058, 0.0323, 0.7913, 0.5775]])

In [12]:
#find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.9419, 0.3062, 0.9409, 0.7417],
        [0.2304, 0.7320, 0.5334, 0.1238],
        [0.8058, 0.0323, 0.7913, 0.5775]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [14]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [15]:
# multiply a tensor by 10

tensor * 10

tensor([10, 20, 30])

In [17]:
# substract 10
tensor - 10

tensor([-9, -8, -7])

In [18]:
# try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [19]:
torch.add(tensor, 10)

tensor([11, 12, 13])