<a href="https://colab.research.google.com/github/mouni001/AI/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [ ]:
#intro to tensors
#A way to represent data


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()


7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector.ndim #number dimention of of the vector
#only look at the pair of squaer brackts

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
 TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png

SyntaxError: invalid syntax (ipython-input-144227728.py, line 1)

### Random Tensors


In [ ]:
#Random tensors
# why random tensors?

# random tensors are important because the way many neural networks learn is that
# they start with tensors full of random numbers and then adjust those random numbers
# to better represent the data

# 'start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers'

# torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.8187, 0.2302, 0.9647, 0.1027],
        [0.8232, 0.1448, 0.1270, 0.4398],
        [0.0072, 0.1759, 0.0830, 0.0797]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones




In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
 zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# use torch.range() but deprecating use aragange instead
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start =0, end=1000, step =77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# creating tensors like
tens_zeros = torch.zeros_like(one_to_ten)
tens_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatype

**Notes:** Tensor datatype is one of the 3 big errors you'll run into Pytorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the irght device

In [ ]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None, #what data type is the tensor (e.g.: float32 or float16)
                               device= None, #what device is your tensor on
                               requires_grad=False)#wether or not to track gradient tensors with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### getting information from tensors (tensors attributes)

1. Tensors not right datatype-to do get datatype from tensor, can use 'tensor.dtype'
2. Tensors not right shape-to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the irght device-to get device from a tensor, can use 'tensor.device'

In [ ]:
# create a tensor
some_tensor =torch.rand(3,4)
some_tensor

tensor([[0.4086, 0.5675, 0.2725, 0.8185],
        [0.5701, 0.1759, 0.5813, 0.2396],
        [0.2396, 0.7142, 0.8229, 0.0997]])

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.4086, 0.5675, 0.2725, 0.8185],
        [0.5701, 0.1759, 0.5813, 0.2396],
        [0.2396, 0.7142, 0.8229, 0.0997]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply a tensor by 10

tensor * 10

tensor([10, 20, 30])

In [ ]:
# substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

####matric multiplication

two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* '(3,2) @ (3,2)' won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work

2. The resulting matrix has he shape of the **outer dimensions**:
* '(2,3) @ (3,2)' -> '(2, 2)'
* '(3,2) @ (2,3)' -> '(3,3)'

In [ ]:
 # element wise mutliplictaion
 print(tensor, "*", tensor)
 print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix multilpication
torch.matmul(tensor, tensor)
# matrix multiplication (1*1 + 2*2 + 3*3)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 379 µs, sys: 1.91 ms, total: 2.29 ms
Wall time: 2.23 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 346 µs, sys: 0 ns, total: 346 µs
Wall time: 260 µs


tensor(14)

### One of the most common error in deep learning

In [ ]:
# shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for torch.matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulate the shape of one of our tensors using the **transpose**.

A**transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# The matrix multiplication operation works when the tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")
torch.mm(tensor_A, tensor_B.T)


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# create a tensor
x= torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the position in the tensor that has the minimum value with argmin () -> returns index position of targt tensor where minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# find the position in tensor that has the maximum value argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking - combine multiple tensors on top of each otehr (vstack) or side by side(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add '1' dimension to a target tensor
* Permute - Return a view of the iput with domensions permuted (swapped) in a certain way

In [ ]:
# let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimention
x_reshaped = x.reshape(1,9) # needs to be the same dimension as the original (1*9)= 9
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because a vieww of a tensor shares the same memory as the original )
z[:, 0] = 5 #change the first element to 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_staxked = torch.stack([x,x,x,x], dim=0) #difault dimension
x_staxked #theres also vstack and hstack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#  torch.queeze() - removes all simgle dimensions from a target temsor
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x2_unsqueezed = x_unsqueezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
print(f"New shape: {x2_unsqueezed.shape}")
x2_unsqueezed

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])
New shape: torch.Size([1, 1, 9])


tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
# torch.permute - rearange the dimensions of a target tensor in a specific order
x_original = torch.rand(size=(224,190,3))# [height, width, colour_channels]
# per,ute the orginal tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]

Previous shape: torch.Size([224, 190, 3])
New shape: torch.Size([3, 224, 190])


## Indexing (selecting data from tensors)

indexing with Pytorch is similar to indexing with Numpy.

In [ ]:
# create a tensor
import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# let's index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# lets index on the middle bracket (dim = 1)

x[0][0] # or x[0,0]



tensor([1, 2, 3])

In [ ]:
# let's index in most inner bracket (last dimension)
x[0][1][1]


tensor(5)

In [ ]:
# you can also use ":" to select "all" of a target dimension

x[:,0] # get all of dim = 0


tensor([[1, 2, 3]])

In [ ]:
# get all of 0th and 1st dimension but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1] #answer has square brakets

tensor([5])

In [ ]:
# get index 0 of the 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# index on x to return 9
print(x[0,2, 2])

#index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


##pytorch tensors and Numpy

Numpy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> 'torch.from_numpy(ndarray)'
* PyTorch tensor -> Numpy -> 'torch.Tensor.numpy()'

In [ ]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype


dtype('float64')

In [ ]:
# change the value of array, what will this do to 'tensor'
array = array + 1
array, tensor #new tensor in memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to Nympy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor, what happens to 'numpy_tensor'
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how neural network learns:

'tart with random numbers -> tensors operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...'

To reduce the randomness in neural netwoks and Pytorch comes the concept of a **random seed**.
Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch
# create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B) #check if the value are equal


tensor([[0.9720, 0.8639, 0.6288, 0.5655],
        [0.1829, 0.7577, 0.1828, 0.7317],
        [0.6338, 0.5267, 0.2046, 0.6086]])
tensor([[0.2666, 0.6472, 0.0049, 0.8981],
        [0.4313, 0.2073, 0.1626, 0.4208],
        [0.1877, 0.7383, 0.8580, 0.8038]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # we need to call again so it gives true
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra sources:
https://docs.pytorch.org/docs/stable/notes/randomness.html

## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPUs = fatser computattion on numbers, thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything hunky dory (good)



### Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get
3. Use cloud computing - GCP, AWS Azure, these services allow you to rent computers on te cloud and access them

For 2, 3 Pytorch + GPU drivers (CUDA)

In [ ]:
invidia-smi

NameError: name 'invidia' is not defined

###2. chek for GPU acess with Pytorch

In [ ]:
#checkfor GPU access with Pytorch
import torch
torch.cuda.is_available()

False

In [ ]:
# Setup device agnositic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# count the nuber of devices
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU
the reason we want our tensors/models on the GPU is beacuse using a GPU results in faster computations.

In [ ]:
# create a tensor (default on the CPU)

tensor = torch.tensor([1,2,3], device = "cpu")

#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to CPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. moving tensors back to CPU

In [ ]:
# if tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
# to fit the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])