<a href="https://colab.research.google.com/github/mouni001/AI/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
#intro to tensors
#A way to represent data


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()


7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector.ndim #number dimention of of the vector
#only look at the pair of squaer brackts

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
 TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png

SyntaxError: invalid syntax (<ipython-input-24-4a8d36e4d0ee>, line 1)

### Random Tensors


In [ ]:
#Random tensors
why random tensors?

random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those random numbers
to better represent the data

'start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers'

torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.8584, 0.1119, 0.2560, 0.6149],
        [0.2110, 0.2176, 0.3771, 0.0281],
        [0.5777, 0.9467, 0.5672, 0.4039]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones




In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
 zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# use torch.range() but deprecating use aragange instead
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start =0, end=1000, step =77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# creating tensors like
tens_zeros = torch.zeros_like(one_to_ten)
tens_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatype

**Notes:** Tensor datatype is one of the 3 big errors you'll run into Pytorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the irght device

In [ ]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None, #what data type is the tensor (e.g.: float32 or float16)
                               device= None, #what device is your tensor on
                               requires_grad=False)#wether or not to track gradient tensors with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### getting information from tensors (tensors attributes)

1. Tensors not right datatype-to do get datatype from tensor, can use 'tensor.dtype'
2. Tensors not right shape-to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the irght device-to get device from a tensor, can use 'tensor.device'

In [ ]:
# create a tensor
some_tensor =torch.rand(3,4)
some_tensor

tensor([[0.9419, 0.3062, 0.9409, 0.7417],
        [0.2304, 0.7320, 0.5334, 0.1238],
        [0.8058, 0.0323, 0.7913, 0.5775]])

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.9419, 0.3062, 0.9409, 0.7417],
        [0.2304, 0.7320, 0.5334, 0.1238],
        [0.8058, 0.0323, 0.7913, 0.5775]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply a tensor by 10

tensor * 10

tensor([10, 20, 30])

In [ ]:
# substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

####matric multiplication

two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* '(3,2) @ (3,2)' won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work

2. The resulting matrix has he shape of the **outer dimensions**:
* '(2,3) @ (3,2)' -> '(2, 2)'
* '(3,2) @ (2,3)' -> '(3,3)'

In [ ]:
 # element wise mutliplictaion
 print(tensor, "*", tensor)
 print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix multilpication
torch.matmul(tensor, tensor)
# matrix multiplication (1*1 + 2*2 + 3*3)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.68 ms, sys: 869 µs, total: 2.55 ms
Wall time: 4.88 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 320 µs, sys: 0 ns, total: 320 µs
Wall time: 243 µs


tensor(14)

### One of the most common error in deep learning

In [ ]:
# shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for torch.matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulate the shape of one of our tensors using the **transpose**.

A**transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# The matrix multiplication operation works when the tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")
torch.mm(tensor_A, tensor_B.T)


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [11]:
# create a tensor
x= torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [3]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [4]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [5]:
# find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [6]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [12]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [13]:
# find the position in the tensor that has the minimum value with argmin () -> returns index position of targt tensor where minimum value occurs
x.argmin()

tensor(0)

In [14]:
x[0]

tensor(1)

In [15]:
# find the position in tensor that has the maximum value argmax()
x.argmax()

tensor(9)

In [16]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking - combine multiple tensors on top of each otehr (vstack) or side by side(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add '1' dimension to a target tensor
* Permute - Return a view of the iput with domensions permuted (swapped) in a certain way

In [17]:
# let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [18]:
# add an extra dimention
x_reshaped = x.reshape(1,9) # needs to be the same dimension as the original (1*9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [19]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [21]:
# changing z changes x (because a vieww of a tensor shares the same memory as the original )
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [24]:
# Stack tensors on top of each other
x_staxked = torch.stack([x,x,x,x], dim=0)
x_staxked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [25]:
#  torch.queeze() - removes all simgle dimensions from a target temsor
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [30]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [31]:
# torch unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [32]:
# torch.permute - rearange the dimensions of a target tensor in a specific order
x_original = torch.rand(size=(224,224,3))# [height, width, colour_channels]
# per,ute the orginal tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

indexing with Pytorch is similar to indexing with Numpy.

In [34]:
# create a tensor
import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [35]:
# let's index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
# lets index on the middle bracket (dim = 1)

x[0][0]



tensor([1, 2, 3])

In [39]:
# let's index in most inner bracket (last dimension)
x[0][1][1]


tensor(5)

In [40]:
# you can also use ":" to select "all" of a target dimension

x[:,0] # get all of dim = 0


tensor([[1, 2, 3]])

In [41]:
# get all of 0th and 1st dimension but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [42]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# get index 0 of the 0th and 1st dimension and all values of 2nd dimension